### ISSUE TITLE
[Bug] unstable-quests: null metaMonsters: unable to set name.

### ISSUE THREAD

**Issue by scooterboo** [Melledy/Grasscutter#2114]
**Did you look for other closed issues that have the same problem?**
Yes

**Describe the bug**
When setting a name, the continue button doesn't work and a null pointer exception appears in the server log (see attachments).
emu\grasscutter\game\entity\EntityMonster.java does not seem to handle the case where metaMonster is null on line 241.

I am unsure if it should be handled or that there is a bigger issue where metaMonster should never be null.

**Which branch did you use?**
  Grasscutter version: 2.0.0-unstable-quests
  Git Hash: 47cdfe5c

**Screenshots**
![380](https://user-images.githubusercontent.com/1877986/231908934-6802853e-3ff7-4c4a-900d-a5f60cfea4d7.png)
![384](https://user-images.githubusercontent.com/1877986/231908942-76aeacf7-d33c-48ee-8c6f-98cf2495021f.png)
![385](https://user-images.githubusercontent.com/1877986/231908952-4a4b4705-41ba-435b-a1d9-0d29b7d5071c.png)

**Comment by scooterboo** [comment]
First error caused by 349f76b
second error caused by d6efaae when Questing is true

**Comment by KingRainbow44** [comment]
First error fixed in [`eda5e8c5`](https://github.com/Grasscutters/Grasscutter/commit/eda5e8c5e0760ff351df0ddc0575d454f6c5c4da)

**Comment by KingRainbow44** [comment]
please try again with the bug fix above ^^
second error should be fixed by the first

**Comment by scooterboo** [comment]
> please try again with the bug fix above ^^
> second error should be fixed by the first

Second error still happens. Do you want a new ticket for it?
![image](https://user-images.githubusercontent.com/1877986/231922779-8002c764-ad13-4918-a99e-6f1557de9e54.png)

**Comment by eternalcomet** [comment]
maybe bacause @KingRainbow44 create a new thread to load scripts but it is not thread-safety
see https://github.com/Grasscutters/Grasscutter/commit/b0ab0c68ad95ef86aae29f07867af7f484c82582

**Comment by eternalcomet** [comment]
> maybe bacause @KingRainbow44 create a new thread to load scripts but it is not thread-safety see [b0ab0c6](https://github.com/Grasscutters/Grasscutter/commit/b0ab0c68ad95ef86aae29f07867af7f484c82582)

@scooterboo revert this and have a try.

**Comment by scooterboo** [comment]
> > maybe bacause @KingRainbow44 create a new thread to load scripts but it is not thread-safety see [b0ab0c6](https://github.com/Grasscutters/Grasscutter/commit/b0ab0c68ad95ef86aae29f07867af7f484c82582)
> 
> @scooterboo revert this and have a try.

While it's true the error didn't happen, immediately all quests in the game then ran at the same time.

**Comment by KingRainbow44** [comment]
> immediately all quests in the game then ran at the same time

this is probably a result of the new call to `onPlayerBorn`

**Comment by KingRainbow44** [comment]
this issue was fixed as of `2a5c7bf7`
