### ISSUE TITLE
Unable to save game data normally

### ISSUE THREAD

**Issue by yuexuanblog** [Melledy/Grasscutter#679]
When I exit the game normally and re-enter the game, I find that the team configuration and the location of the characters have not been saved
(baidu translate)

Development branch

**Screenshots**

For example: my original character is located at a, and then when I get to B and quit the game Re - enter the game and find yourself still at point a, and the team configuration has been restored I don't know if there are any other data not saved
(baidu translate)

**Comment by 1-lavender-1** [comment]
我也遇到过这个问题，后来通过重启服务端和数据库自动解决了

I also encountered this issue, and it was solved automatically by restarting the server and database

**Comment by yuexuanblog** [comment]
> 我也遇到过这个问题，后来通过重启服务端和数据库自动解决了
> 
> 我也遇到了这个问题，重启服务器和数据库就自动解决了

The method you provided has just been tested, but the problem has not been solved I still can't save location and team configuration data

**Comment by misaka10843** [comment]
It feels like there should be a problem after one of the merges yesterday
Because I was able to save the day before yesterday after changing the team configuration, but yesterday afternoon I found that I could not save the location after changing

---
**Chinese:**

感觉应该是昨天的某次合并后出现的问题
因为我在前天更改了队伍配置后还可以保存，但是昨天下午发现更改后就无法保存位置了

**Comment by lunaticwhat** [comment]
can you try to log out the game before exit the game ?

**Comment by yuexuanblog** [comment]
> 可以在退出游戏前先退出游戏吗？
Log out of the game normally without forced shutdown

**Comment by fkc4** [comment]
My Holy Relic has no affixes, oh my friend ! help me!
